backend:
  image:
    repository: sybew/location
    tag: 749d2cd7
    pullPolicy: Always

  nameOverride: location
  fullnameOverride: location
  databaseName: location
  ingress:
    enabled: false
