
# Tự động thêm cấu hình Ingress để tránh xung đột với namespace yas
ingress:
  enabled: true
  hosts:
    - host: api.dev.yas.local.com
      paths:
        - path: /swagger-ui
          pathType: ImplementationSpecific
