backend:
  image:
    repository: sybew/promotion
    tag: main
    pullPolicy: Always

  nameOverride: promotion
  fullnameOverride: promotion
  databaseName: promotion
  ingress:
    enabled: false
