apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-service
  template:
    metadata:
      labels:
        app: tax-service
    spec:
      containers:
      - name: tax-service
        image: docker.io/library/nginx:alpine # Tạm thời để nginx để test kết nối trước khi build image YAS thật
        ports:
        - containerPort: 80
